### ISSUE TITLE
RFC: make leveldb an optional dependency

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-datastore-level#17]
I'm very much interested in lowering the barriers to entry for js-ipfs. One of the problems new developers frequently have is toolchains for compiling native modules. Often new developers don't have the necessary knowledge to understand an `npm install` error relating to compiling a native module, nor the ability to resolve that error without help.

Moreover, we _should not_ require frontend developers looking to bundle js-ipfs in their webapp to compile leveldb or install the toolchains to do so.

Can we please make leveldb an optional dependency and fallback to leveljs?

**Comment by olizilla** [comment]
Is there any reason not to do that? It sounds like an improvement to me.

**Comment by vweevers** [comment]
FWIW the recent update to `leveldown@5` should improve the situation, because prebuilt binaries are now included in the npm package (no extra download step), and they are runtime-agnostic (Node and Electron use the same binary) and forwards-compatible with future Node.js/Electron versions.

> Is there any reason not to do that?

There is a downside, yes: if a user _does_ want to use LevelDB, but their build failed on `npm install` for whatever reason, then npm will continue as if nothing bad happened. That situation might be worse because the user possibly won't know things are broken until run time.

**Comment by mikeal** [comment]
Can’t we just ship with a more specific level datastore that is implemented in pure JavaScript? There are several pure JS leveldown implementations AFAIK.

**Comment by vweevers** [comment]
@mikeal That are actively maintained, persistent, fast and have the same features? The short answer is no. Maybe, if IPFS only uses a subset of features. There's also been interest in creating a WebAssembly build of LevelDB but AFAIK it's not possible yet due to its async IO.

I want to stress that for most users there is no compile step anymore.

**Comment by mikeal** [comment]
.@rvagg mentioned a good lsm tree leveldown in pure JS, I’ll let him link to it here.

TBH though, shipping with a slightly slower but much nicer to install leveldown seems fine. Many of these installs end up just being for webpack bundling anyway, and we can write some good docs for people running `js-ipfs` as a Node.js service for how to swap in more performant leveldown implementations.

**Comment by vweevers** [comment]
> a good lsm tree leveldown in pure JS

Oh! I'm interested (for unrelated use cases).

What features does the store need beyond simple puts and gets? E.g. iterators, snapshotting, seeking, binary support, ...?

**Comment by vweevers** [comment]
(I'm also asking because `level-js` will likely drop snapshotting, in favor of proper backpressure)

**Comment by rvagg** [comment]
ummm I can't find it now! but I also don't recall it being level* compatible, more just an attempt to implement the algorithm in JS, on top of JSON storage I think. I'll keep looking cause I'm in a general algorithm-hunt mode anyway and am really keen to abstract some LSM concepts on top of IPLD. I'm also interested in toying with some IPLD-block storage ideas I have rattling around in my head and perhaps that'll be helpful here. It seems to me that level is probably not be the best backend for this anyway and we could do something even more efficient in pure JS focusing only on the performance characteristics that are important - level is great for general performance but only a subset of that matters here.

**Comment by achingbrain** [comment]
> I want to stress that for most users there is no compile step anymore

I think this has addressed the original issue.  Please reopen if people still have to compile leveldown during an install.
